export const colors = {
    dayMode: {
        submitBtn: {
            bgColor: "#0061E6",
            color: "#FFFFFF",
            hoverBg: "#004ab3",
            disabled: "#747EA1",
        },
        cancelBtn: {
            bgColor: "#FFA4161A",
            disabled: "rgb(153, 94, 0, 0.6)",
            color: "#FFA416",
            sbColor: "#616161",
            border: "#FFA4164D",
        },
        stillBtn: {
            bgColor: "#F3F6FB",
            disabled: "#808080",
            color: "#0061E6",
            borderColor: "#BDC1DF",
        },
        setUpBtn: {
            bgColor: "#0061E6",
            disabled: "#808080",
            color: "#FFFFFF",
            borderColor: "#0061E6",
            diText: "#FFFFFF",
        },
        hallowBtn: {
            bgColor: "transparent",
            disabled: "#808080",
            color: "#0061E6",
            borderColor: "#BDC1DF",
        },
        AuthenticatorBtn: {
            bgColor: "#BDC1DF",
            disabled: "rgb(117, 126, 189, 0.5)",
            color: "#10152B",
            borderColor: "#BDC1DF",
            hoverBg: "#a9aed6",
        },
        signUpBtn: {
            bgColor: "transparent",
            disabled: "transparent",
            disabledBorder: "#747EA1",
            color: "#0061E6",
            borderColor: "#0061E6",
            hoverBg: "transparent",
            hoverBorder: "#004ab3",
        },
        mainBody: {
            background: "#101439",
            backgroundLight: "#1c244c",
            backgroundDark: "#0c0f27",
            bgPattern: "#ffffff08",
            sidebarBg: "#606993",
            cardBorder: "#21264a",
            cardBg: "#1a1f3f",
            cardLight: "#222647",
            cardDark: "#1a1f3f",
            sideMenu: "#15193c",
            blueText: "#0061E6",
            yellow: "#FFA416",
        },
    },

    // Dark mode colors

    nightMode: {
        submitBtn: {
            bgColor: "#0061E6",
            color: "#FFFFFF",
            hoverBg: "#004ab3",
            disabled: "#747EA1",
        },
        cancelBtn: {
            bgColor: "#FFA4161A",
            disabled: "rgb(153, 94, 0, 0.6)",
            color: "#FFA416",
            sbColor: "#616161",
            border: "#FFA4164D",
        },
        stillBtn: {
            bgColor: "#1D243A",
            disabled: "#808080",
            color: "#0061E6",
            borderColor: "#1D243A",
        },
        setUpBtn: {
            bgColor: "#1D243A",
            disabled: "#2A3149",
            color: "#FFFFFF",
            borderColor: "#1D243A",
            diText: "#747EA1",
        },
        hallowBtn: {
            bgColor: "transparent",
            disabled: "#808080",
            color: "#FFFFFF",
            borderColor: "#272727",
        },
        AuthenticatorBtn: {
            bgColor: "#10152B",
            disabled: "rgb(55, 72, 149, 0.5)",
            color: "#FFFFFF",
            borderColor: "#10152B",
            hoverBg: "#1c244a",
        },
        signUpBtn: {
            bgColor: "transparent",
            disabled: "transparent",
            disabledBorder: "#747EA1",
            color: "#0061E6",
            borderColor: "#0061E6",
            hoverBg: "transparent",
            hoverBorder: "#004ab3",
        },
        mainBody: {
            background: "#101439",
            backgroundLight: "#1c244c",
            backgroundDark: "#0c0f27",
            bgPattern: "#ffffff08",
            sidebarBg: "#292e55",
            cardBorder: "#22264a",
            cardBg: "#1a1f3f",
            cardLight: "#242949",
            cardDark: "#161a36",
            sideMenu: "#13173a",
            blueText: "#0061E6",
            yellow: "#FFA416",
        },
    },
};
